function drawBulletBill(x,y,scale) {
    ctx.save();
    ctx.translate(x*UNIT,y*UNIT);
    ctx.scale(scale,scale);

    
    ctx.fillStyle = "black";
    ctx.fillRect(0,0,2*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,0,6*UNIT,1*UNIT);
    ctx.fillRect(2*UNIT,1*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(9*UNIT,1*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(3*UNIT,2*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(10*UNIT,2*UNIT,4*UNIT,1*UNIT);
    ctx.fillRect(0,3*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(3*UNIT,3*UNIT,8*UNIT,1*UNIT);
    ctx.fillRect(12*UNIT,3*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,4*UNIT,11*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,5*UNIT,11*UNIT,1*UNIT);
    ctx.fillRect(13*UNIT,4*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(13*UNIT,5*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(15*UNIT,5*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(0,6*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(7*UNIT,6*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(15*UNIT,6*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,7*UNIT,4*UNIT,1*UNIT);
    ctx.fillRect(7*UNIT,7*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(10*UNIT,7*UNIT,6*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,8*UNIT,4*UNIT,1*UNIT);
    ctx.fillRect(11*UNIT,8*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,9*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,10*UNIT,7*UNIT,1*UNIT);
    ctx.fillRect(11*UNIT,9*UNIT,4*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,11*UNIT,7*UNIT,1*UNIT);
    ctx.fillRect(10*UNIT,10*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(7*UNIT,11*UNIT,7*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,12*UNIT,12*UNIT,1*UNIT);
    ctx.fillRect(0*UNIT,13*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,13*UNIT,6*UNIT,1*UNIT);
    ctx.fillStyle = "#ABAAA6";
    ctx.fillRect(2*UNIT,0,2*UNIT,1*UNIT);
    ctx.fillRect(0,2*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,2*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(2*UNIT,3*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(9*UNIT,3*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,8*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(5*UNIT,9*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(7*UNIT,10*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(10*UNIT,9*UNIT,1*UNIT,1*UNIT);
    ctx.fillStyle = "white";
    ctx.fillRect(0,1*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(2*UNIT,2*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,1*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(9*UNIT,2*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(11*UNIT,3*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(11*UNIT,4*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(11*UNIT,5*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(12*UNIT,6*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(14*UNIT,5*UNIT,1*UNIT,1*UNIT);
    ctx.fillRect(5*UNIT,6*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(4*UNIT,7*UNIT,3*UNIT,1*UNIT);
    ctx.fillRect(6*UNIT,8*UNIT,5*UNIT,1*UNIT);
    ctx.fillRect(8*UNIT,7*UNIT,2*UNIT,1*UNIT);
    ctx.fillRect(8*UNIT,9*UNIT,2*UNIT,1*UNIT);
    ctx.restore();
}